### PR TITLE
REGTEST Added unit test for shutdown

### PR DESCRIPTION
**Pull request by pierresouchay**

### CODE REVIEW

**Comment by aiharos** [comment]
This depends on #28 so I will wait for @ShimmerGlass to review that one before merging this.

**Comment by pierresouchay** [comment]
@aiharos I rebased, this is fine now

**Comment by aiharos** [comment]
> @aiharos I rebased, this is fine now

OK, do you still want to wait for a review from ShimmerGlass?

**Comment by pierresouchay** [comment]
@aiharos No, it does not depend of API refactoring, this is fine to merge

**Comment by aiharos** [comment]
Merged!

**Pull request merged**
