### PR TITLE
Feat/version compare

### PR DESCRIPTION
**Pull request by amelhusic**

### CODE REVIEW

**Comment by gdubicki** [comment]
While we are here shouldn't we rather start checking for version X.*, not > X.Y?

Not only theoretically major semver version uptick may cause issues but as issue #6 shows it also happens in practice.

**Comment by amelhusic** [comment]
Hi @gdubicki. Not sure what do you mean by `X.*`?
HAProxy semver versions are in either `major.minor` or `major.minor.patch` format.
Dataplaneapi follows `major.minor.patch` format.

[Here](https://github.com/haproxytech/haproxy-consul-connect/pull/56/commits/5b057bd4fef3bae0c3401c2a62f3ee3f5d0db7c2#diff-a212247fc69b0de9bb8fa07c53416582R139) we check minimum required versions.

**Comment by gdubicki** [comment]
I mean that I think that we should test if the major version is equal to expected, not equal or greater than.

**Comment by amelhusic** [comment]
Got it. @ShimmerGlass what do you think?

**Comment by ShimmerGlass** [comment]
I agree with @gdubicki, it's probably better to require a specific major version

**Comment by amelhusic** [comment]
It makes sense to me too. Updated.

**Pull request merged**
