### PR TITLE
Upgrade to dataplaneapi v2

### PR DESCRIPTION
**Pull request by ShimmerGlass**
The API path for dataplane api now use the /v2 prefix. 

Fixes: #6

### CODE REVIEW

**Comment by aiharos** [comment]
There will be some (not many) incompatible API changes between dataplanes v1 and v2. We should postpone merging until after v2 is released and we can review any potential other changes that need to be made - this would have an impact on supporting multiple dataplane versions too.

Having said that, the dataplaneapi v2 should be a direct upgrade with only additional features, so there might be no need to keep using v1.

**Comment by pierresouchay** [comment]
@aiharos Yes, but it supposes to have the new binary for dataplaneapi

**Comment by gdubicki** [comment]
Dataplane API is already in v. 2.0.2, can we merge this please?

**Comment by ShimmerGlass** [comment]
@gdubicki @aiharos rebased and upgraded the models. I added proper logging for the dataplane as well.

@pierresouchay handling multiple versions of the dataplane would be pretty complex (see the size of this patch). However, we could bundle the dataplane with haproxy-connect so people don't have to deploy it and manage its version themselves, simplifying things greatly. We could package it in the binary and extract it to the fs, but I would be in favor of actually running the server from haproxy-connect's code, easier to maintain and debug IMO. @aiharos any thoughts on that?

**Comment by aiharos** [comment]
>  We could package it in the binary and extract it to the fs, but I would be in favor of actually running the server from haproxy-connect's code, easier to maintain and debug IMO. @aiharos any thoughts on that?

By "server" you mean running the dataplaneapi from the consul-connect code, or something else?

**Comment by ShimmerGlass** [comment]
@aiharos yes, running the dataplane from consul-connect

**Comment by ShimmerGlass** [comment]
Rebased. To be clear, I think we can merge this and answer the packaging question in an other PR

**Comment by aiharos** [comment]
> What do you think about handling several versions ?
> what about a flag `--dataplaneapi-version=v2` (for now), once the v2 API is the default, make it the default?
> 

Dataplaneapi v2 is the default now, and since it is a direct superset of features over v1 (and no changes in the API endpoints used by haproxy-consul-connect,  @ShimmerGlass agrees that we can merge this.

**Pull request merged**
