### PR TITLE
REFACTOR Updated references to go mod github.com/haproxytech/haproxy-consul-connect

### PR DESCRIPTION
**Pull request by pierresouchay**
And be sure to apply go fmt

### CODE REVIEW

**Comment by aiharos** [comment]
I apologize for insisting, just amend the commit message to

> REFACTOR: Updated references to go mod github.com/haproxytech/haproxy-consul-connect

And it's perfect! :)

**Comment by pierresouchay** [comment]
@aiharos DONE

**Comment by pierresouchay** [comment]
@aiharos Can I merge it, so I can advance on https://github.com/haproxytech/haproxy-consul-connect/issues/19 ?

**Comment by aiharos** [comment]
Merged!

**Pull request merged**
